# fly.toml app configuration file generated for zoltan-antal-pokedex on 2024-01-04T14:48:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zoltan-antal-pokedex"
primary_region = "lhr"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"
    
[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services]
  processes = ["app"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
